### ISSUE TITLE
Question about anchor chaining algorithm

### ISSUE THREAD

**Issue by cjain7** [lh3/minigraph#8]
Hi Heng,

Thanks for sharing the minigraph preprint.
I've a question about your new anchor chaining algorithm described in the pre-print. I appreciate the use of RMQ data structure to consider a much larger set of anchors while building chains. I'm curious to know the rationale of using different gap costs for anchors in small v/s large windows.

Assuming the gap-cost function to be c_1 ·g_ji  + c_2 ·d_ji  (i'm ignoring the third log term: log2 g_ji for now), it should be possible to process anchors in **both** large and small window by using a RMQ-based algorithm as was described by [Abouelhoda and Ohlebusch, 2005](https://doi.org/10.1016/j.jda.2004.08.011)  (section 4.2.1). Their paper refers to the above cost function as "sum-of-pairs" gap cost model. Wondering if you also considered implementing the chaining algorithm that way? I think this would allow you to compute optimal chains in all scenarios. Although if the third log term plays an important role, then this won't work.

Also, did you observe any significant runtime (or memory) overhead using the new chaining algorithm of minigraph over chaining algorithm in minimap2?

Thanks in advance!

**Comment by lh3** [comment]
Implementing sum-of-pairs cost requires a 2-d RMQ, I think. It is more complex and I don't have an efficient implementation for that. Abouelhoda and Ohlebusch use a k-d tree in their "chainer". Ref 52 in my preprint suggests that is inefficient. Ref 52 does provide an implementation, clasp, but I believe it is not applicable to my case. I need a dynamic structure to avoid large memory. There may be a better way to implement sum-of-pairs cost to meet my needs. I haven't found yet, or maybe I haven't tried hard enough. Another minor reason for the minigraph heuristic is that sum-of-pairs doesn't easily handle overlapping anchors; DP is easier in that case.

> Also, did you observe any significant runtime (or memory) overhead using the new chaining algorithm of minigraph over chaining algorithm in minimap2?

minigraph introduces a new chaining heuristic mainly because the minimap2 heuristic doesn't work well with long segdups when we allow large gaps. With the new heuristic, minigraph under 100kb gap length achieves comparable speed to minimap2 under 10kb gap length. The memory is also comparable because the dynamic RMQ tree is often much smaller than the full list of anchors.

**Comment by cjain7** [comment]
Thank you for the quick response.

> Implementing sum-of-pairs cost requires a 2-d RMQ, I think.
You're absolutely right. Thanks for sharing Ref 52, this is good to know. 

> sum-of-pairs doesn't easily handle overlapping anchors
I see. This also reminds me of a recent work that you might already be aware of. Haven't read the paper myself, so not sure if it would help. 
["Chaining with overlaps revisited" 2020](https://arxiv.org/pdf/2001.06864.pdf)

**Comment by lh3** [comment]
Reference numbers are changed due to the recent update to the manuscript. For a record, ref 52 in this thread refers to [Otto et al (2011)](https://almob.biomedcentral.com/articles/10.1186/1748-7188-6-4).
